version: "3.9"

services:
  pygame-app:
    build: .
    volumes:
      - pygame-code:/app   # Monta el c√≥digo local dentro del contenedor
    stdin_open: true
    tty: true
    command: python Ejercicio2a.py

# ---------------------------------------------------
# Volumen top-level (gestionado por Docker)
# ---------------------------------------------------
volumes:
  pygame-code:
